apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bcrstracking.fullname" . }}
  labels:
    {{- include "bcrstracking.labels" . | nindent 4 }}
type: Opaque
data:
  CLICKHOUSE_PASSWORD: {{ .Values.secret.clickhousePassword | default "" | b64enc | quote }}
