apiVersion: v1
kind: Service
metadata:
  name: {{ include "bcrstracking.fullname" . }}
  labels:
    {{- include "bcrstracking.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "bcrstracking.selectorLabels" . | nindent 4 }}
